services:
  registry:
    image: registry:2
    restart: always
    container_name: myregistry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTICATE : /certs/myregistry.crt
      REGISTRY_HTTP-TLS_KEY: /certs/myregistry.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./passwd:/auth
