version: '3'

services:
  php:
    image: oswald/docker-training:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - MYSQL_ADDON_DB=my_database
      - MYSQL_ADDON_HOST=db
      - MYSQL_ADDON_USER=root
      - MYSQL_ADDON_PASSWORD=password
    networks:
      - front
      - back

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - front

  db:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - "mysqldata:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - back

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - front

networks:
  front: 
  back:

volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local
