services:
  registry:
    image: registry:2
    restart: always
    container_name: myregistry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTICATE : /certs/myregistry.crt
      REGISTRY_HTTP-TLS_KEY: /certs/myregistry.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
    volumes:
      - /home/francois/formation/docker/registre/data:/var/lib/registry
      - /home/francois/formation/docker/registre/certs:/certs
      - /home/francois/formation/docker/registre/passwd:/auth
  app:
    build: .
    image: 127.0.0.1:5000/flask-redis:1.0
    environment:
      - FLASK_ENV=development
    ports:
      - 5010:5000
  redis:
    image: redis:4.0.11-alpine
