version: '3'
services:
  php:
    image: oswald/docker-training:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - MYSQL_ADDON_DB=my_database
      - MYSQL_ADDON_HOST=db
      - MYSQL_ADDON_USER=root
      - MYSQL_ADDON_PASSWORD=password
    networks:
      - front
      - back
  db:
    image: mariadb:10
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - back
networks:
  front: 
  back:
